Repository FC-DEV3-Final-Project/KODAnect-backend-springboot, pull requests merged in 2025-06, with the labels that each got.

#40 fix: 파일 경로 수정
  src/main/resources/application-prod.properties
Labels: bug

#43 Chore/cleanup
  .gitignore
  config/checkstyle/suppressions.xml
  src/main/java/kodanect/common/validation/EgovNotNull.java
  src/main/java/kodanect/common/validation/EgovValidation.java
Labels: refactor

#46 refactor: 예외 처리 로깅 포맷 및 레벨 통일
  pom.xml
  src/main/java/kodanect/common/config/EgovConfigTransaction.java
  src/main/java/kodanect/common/config/LoggingAspect.java
  src/main/java/kodanect/common/exception/config/ArticleExceptionHandler.java
  src/main/java/kodanect/common/exception/config/EgovExcepHndlr.java
  src/main/java/kodanect/common/exception/config/GlobalExcepHndlr.java
  src/main/java/kodanect/common/exception/custom/AbstractCustomException.java
  src/main/java/kodanect/common/exception/custom/ArticleNotFoundException.java
  src/main/java/kodanect/common/exception/custom/FileAccessViolationException.java
  src/main/java/kodanect/common/exception/custom/FileMissingException.java
  src/main/java/kodanect/domain/article/controller/ArticleController.java
  src/main/java/kodanect/domain/article/exception/ArticleNotFoundException.java
  src/main/java/kodanect/domain/article/exception/InvalidBoardCodeException.java
  src/main/java/kodanect/domain/article/repository/BoardCategoryCache.java
  src/main/java/kodanect/domain/article/service/impl/ArticleServiceImpl.java
  src/main/java/kodanect/domain/article/service/impl/FileDownloadServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/log4j2.xml
  src/test/java/config/EgovExcepHndlrTest.java
  src/test/java/kodanect/domain/article/controller/ArticleExceptionHandlerTest.java
  src/test/java/kodanect/domain/article/service/ArticleServiceImplTest.java
Labels: refactor

#50 feat: Sentry SDK 및 릴리즈 설정 연동 (Maven + application.properties)
  Jenkinsfile
  docker-compose.dev.yml
  docker-compose.prod.yml
  pom.xml
  src/main/java/kodanect/common/config/WebMvcConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/test/java/config/SentryTestRunner.java
Labels: feature

#54 fix: Update Jenkins file
  Jenkinsfile
Labels: bug

#56 Fix: config jenkinsfile
  Jenkinsfile
Labels: bug

#49 Refactor/remembrance-validation
  src/main/java/kodanect/common/exception/config/GlobalExcepHndlr.java
  src/main/java/kodanect/common/exception/config/MemorialExceptionHandler.java
  src/main/java/kodanect/common/exception/config/MessageKeys.java
  src/main/java/kodanect/common/util/CursorIdentifiable.java
  src/main/java/kodanect/common/util/EmotionType.java
  src/main/java/kodanect/common/util/MemorialFinder.java
  src/main/java/kodanect/common/util/MemorialReplyFinder.java
  src/main/java/kodanect/common/validation/DonateSeqValidator.java
  src/main/java/kodanect/common/validation/PaginationValidator.java
  src/main/java/kodanect/common/validation/ReplySeqValidator.java
  src/main/java/kodanect/common/validation/ReplyValidator.java
  src/main/java/kodanect/common/validation/SearchValidator.java
  src/main/java/kodanect/domain/remembrance/controller/MemorialController.java
  src/main/java/kodanect/domain/remembrance/controller/MemorialReplyController.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialDetailResponse.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyCreateRequest.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyDeleteRequest.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyResponse.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyUpdateRequest.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialResponse.java
  src/main/java/kodanect/domain/remembrance/dto/common/BlankGroup.java
  src/main/java/kodanect/domain/remembrance/dto/common/PatternGroup.java
  src/main/java/kodanect/domain/remembrance/dto/common/ReplyAuthRequest.java
  src/main/java/kodanect/domain/remembrance/dto/common/ReplyContentHolder.java
  src/main/java/kodanect/domain/remembrance/entity/Memorial.java
  src/main/java/kodanect/domain/remembrance/entity/MemorialReply.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidDonateSeqException.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidEmotionTypeException.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidPaginationRangeException.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidReplySeqException.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidSearchDateFormatException.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidSearchDateRangeException.java
  src/main/java/kodanect/domain/remembrance/exception/MemorialNotFoundException.java
  src/main/java/kodanect/domain/remembrance/exception/MemorialReplyNotFoundException.java
  src/main/java/kodanect/domain/remembrance/exception/MissingReplyContentException.java
  src/main/java/kodanect/domain/remembrance/exception/MissingReplyPasswordException.java
  src/main/java/kodanect/domain/remembrance/exception/MissingReplyWriterException.java
  src/main/java/kodanect/domain/remembrance/exception/MissingSearchDateParameterException.java
  src/main/java/kodanect/domain/remembrance/exception/ReplyAlreadyDeleteException.java
  src/main/java/kodanect/domain/remembrance/exception/ReplyIdMismatchException.java
  src/main/java/kodanect/domain/remembrance/exception/ReplyPasswordMismatchException.java
  src/main/java/kodanect/domain/remembrance/exception/ReplyPostMismatchException.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialReplyRepository.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialRepository.java
  src/main/java/kodanect/domain/remembrance/service/MemorialReplyService.java
  src/main/java/kodanect/domain/remembrance/service/MemorialService.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialReplyServiceImpl.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialServiceImpl.java
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/remembrance/controller/MemorialControllerExceptionTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerExceptionTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialReplyServiceImplTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialServiceImplTest.java
Labels: refactor

#55 Feature/remembrance count info
  src/main/java/kodanect/common/response/CursorPaginationResponse.java
  src/main/java/kodanect/common/util/CursorFormatter.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialDetailResponse.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialReplyRepository.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialRepository.java
  src/main/java/kodanect/domain/remembrance/service/MemorialReplyService.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialReplyServiceImpl.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialServiceImpl.java
Labels: feature

#60 feat: 개발환경용 HikariCP 설정 추가 및 커넥션 누수 탐지 활성화 및 도커 파일 일부 수정
  Dockerfile
  Jenkinsfile
  src/main/java/kodanect/common/exception/config/SentryTestRunner.java
  src/main/resources/application-prod.properties
Labels: bug

#63 fix: 댓글 수정 및 커서 직렬화 제거
  src/main/java/kodanect/common/util/CursorIdentifiable.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialDetailResponse.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyResponse.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyUpdateRequest.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialReplyRepository.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialReplyServiceImpl.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialControllerTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerExceptionTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialReplyServiceImplTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialServiceImplTest.java
Labels: refactor

#64 merge: dev 브랜치 최신 수정사항(main 병합) - Sentry 설정, Jenkinsfile, 댓글/커서 개선
  Jenkinsfile
  src/main/java/kodanect/common/exception/config/GlobalExcepHndlr.java
  src/main/java/kodanect/common/exception/config/SentryTestController.java
  src/main/java/kodanect/common/exception/config/SentryTestRunner.java
  src/main/java/kodanect/common/util/CursorIdentifiable.java
  src/main/java/kodanect/domain/article/repository/BoardCategoryCache.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialDetailResponse.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyResponse.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyUpdateRequest.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialReplyRepository.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialReplyServiceImpl.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialControllerTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerExceptionTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialReplyServiceImplTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialServiceImplTest.java
Labels: refactor

#66 refactor: remembrance 변수명 통일
  src/main/java/kodanect/common/util/FormatUtils.java
  src/main/java/kodanect/domain/remembrance/controller/.gitkeep
  src/main/java/kodanect/domain/remembrance/controller/MemorialController.java
  src/main/java/kodanect/domain/remembrance/dto/.gitkeep
  src/main/java/kodanect/domain/remembrance/entity/.gitkeep
  src/main/java/kodanect/domain/remembrance/repository/.gitkeep
  src/main/java/kodanect/domain/remembrance/repository/MemorialReplyRepository.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialRepository.java
  src/main/java/kodanect/domain/remembrance/service/MemorialService.java
  src/main/java/kodanect/domain/remembrance/service/impl/.gitkeep
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialReplyServiceImpl.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialServiceImpl.java
Labels: refactor

#61 refactor/recipientletters
  pom.xml
  src/main/java/kodanect/common/exception/config/MessageKeys.java
  src/main/java/kodanect/common/exception/custom/InvalidIntegerConversionException.java
  src/main/java/kodanect/common/exception/custom/RecipientExceptionHandler.java
  src/main/java/kodanect/common/response/CursorPaginationResponse.java
  src/main/java/kodanect/common/util/CursorFormatter.java
  src/main/java/kodanect/common/util/HcaptchaService.java
  src/main/java/kodanect/domain/recipient/controller/RecipientCommentController.java
  src/main/java/kodanect/domain/recipient/controller/RecipientController.java
  src/main/java/kodanect/domain/recipient/dto/CommentDeleteRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientDeleteRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientDetailResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientListResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientSearchCondition.java
  src/main/java/kodanect/domain/recipient/entity/RecipientCommentEntity.java
  src/main/java/kodanect/domain/recipient/entity/RecipientEntity.java
  src/main/java/kodanect/domain/recipient/exception/RecipientCommentNotFoundException.java
  src/main/java/kodanect/domain/recipient/exception/RecipientInvalidDataException.java
  src/main/java/kodanect/domain/recipient/exception/RecipientInvalidPasscodeException.java
  src/main/java/kodanect/domain/recipient/exception/RecipientNotFoundException.java
  src/main/java/kodanect/domain/recipient/service/RecipientCommentService.java
  src/main/java/kodanect/domain/recipient/service/RecipientService.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImpl.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
  src/test/java/kodanect/domain/recipient/controller/RecipientCommentControllerTest.java
  src/test/java/kodanect/domain/recipient/controller/RecipientControllerTest.java
  src/test/java/kodanect/domain/recipient/repository/RecipientCommentRepositoryTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImplTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceContentValidationTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceImplTest.java
  src/test/java/kodanect/domain/recipient/service/impl/insertRecipientServiceImplTest.java
  src/test/java/kodanect/domain/recipient/service/impl/pagingSearchRecipientServiceImplTest.java
  src/test/java/kodanect/domain/recipient/service/impl/updateDeleteRecipientServiceImplTest.java
Labels: refactor

#65 fix: Jenkins 수정 및 게시판 리펙토링
  Jenkinsfile
  src/main/java/kodanect/domain/article/controller/ArticleController.java
  src/main/java/kodanect/domain/article/dto/ArticleDetailDto.java
  src/main/java/kodanect/domain/article/dto/SearchCondition.java
  src/main/java/kodanect/domain/article/repository/ArticleRepository.java
  src/main/java/kodanect/domain/article/service/impl/ArticleServiceImpl.java
  src/test/java/kodanect/domain/article/controller/ArticleControllerIntegrationTest.java
  src/test/java/kodanect/domain/article/controller/ArticleControllerTest.java
  src/test/java/kodanect/domain/article/repository/ArticleRepositoryTest.java
  src/test/java/kodanect/domain/article/service/ArticleServiceImplTest.java
Labels: refactor

#69 refactor : 게시물 수정 API 25_0611_4
  src/main/java/kodanect/domain/recipient/controller/RecipientController.java
  src/main/java/kodanect/domain/recipient/dto/RecipientRequestDto.java
  src/main/java/kodanect/domain/recipient/service/RecipientService.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
  src/test/java/kodanect/domain/recipient/controller/RecipientCommentControllerTest.java
  src/test/java/kodanect/domain/recipient/controller/RecipientControllerTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceContentValidationTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceImplTest.java
Labels: refactor

#70 refactor / 응답 API 중복 출력 수정_25_0611_6
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientDetailResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientListResponseDto.java
Labels: refactor

#73 merge: 댓글 비밀번호 인증 및 리팩토링, 설정 수정_25_0611
  Jenkinsfile
  src/main/java/kodanect/common/config/WebMvcConfig.java
  src/main/java/kodanect/common/exception/config/MessageKeys.java
  src/main/java/kodanect/domain/article/repository/ArticleRepositoryImpl.java
  src/main/java/kodanect/domain/recipient/controller/RecipientController.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientDetailResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientListResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientRequestDto.java
  src/main/java/kodanect/domain/recipient/service/RecipientService.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
  src/main/java/kodanect/domain/remembrance/controller/MemorialReplyController.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyCreateRequest.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyPasswordRequest.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialReplyUpdateRequest.java
  src/main/java/kodanect/domain/remembrance/service/MemorialReplyService.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialReplyServiceImpl.java
  src/main/resources/egovframework/message/message-common.properties
  src/main/resources/log4j2.xml
  src/test/java/kodanect/domain/recipient/controller/RecipientCommentControllerTest.java
  src/test/java/kodanect/domain/recipient/controller/RecipientControllerTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceContentValidationTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceImplTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerExceptionTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialReplyControllerTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialReplyServiceImplTest.java
Labels: feature

#74 Feature/infra
  Jenkinsfile
  src/main/resources/application-test.properties
Labels: bug

#77 fix: bug fix CORS
  Jenkinsfile
  src/main/java/kodanect/common/config/WebMvcConfig.java
  src/main/java/kodanect/domain/article/controller/ArticleController.java
  src/main/java/kodanect/domain/article/repository/ArticleFileRepository.java
  src/main/java/kodanect/domain/article/repository/ArticleRepository.java
  src/main/java/kodanect/domain/article/repository/ArticleRepositoryCustom.java
  src/main/java/kodanect/domain/article/repository/ArticleRepositoryImpl.java
  src/main/java/kodanect/domain/article/repository/BoardCategoryCache.java
  src/main/java/kodanect/domain/article/repository/BoardCategoryRepository.java
  src/main/java/kodanect/domain/article/service/ArticleService.java
  src/main/java/kodanect/domain/article/service/FileDownloadService.java
  src/main/java/kodanect/domain/article/service/impl/ArticleServiceImpl.java
  src/main/java/kodanect/domain/article/service/impl/FileDownloadServiceImpl.java
  src/main/resources/application-test.properties
  src/test/java/kodanect/domain/article/controller/ArticleControllerIntegrationTest.java
  src/test/java/kodanect/domain/article/controller/ArticleControllerTest.java
  src/test/java/kodanect/domain/article/controller/ArticleExceptionHandlerTest.java
Labels: refactor

#78 merge: bug fix CORS 수정_25_0612
  Jenkinsfile
  src/main/java/kodanect/common/config/WebMvcConfig.java
  src/main/java/kodanect/domain/article/controller/ArticleController.java
  src/main/java/kodanect/domain/article/repository/ArticleFileRepository.java
  src/main/java/kodanect/domain/article/repository/ArticleRepository.java
  src/main/java/kodanect/domain/article/repository/ArticleRepositoryCustom.java
  src/main/java/kodanect/domain/article/repository/ArticleRepositoryImpl.java
  src/main/java/kodanect/domain/article/repository/BoardCategoryCache.java
  src/main/java/kodanect/domain/article/repository/BoardCategoryRepository.java
  src/main/java/kodanect/domain/article/service/ArticleService.java
  src/main/java/kodanect/domain/article/service/FileDownloadService.java
  src/main/java/kodanect/domain/article/service/impl/ArticleServiceImpl.java
  src/main/java/kodanect/domain/article/service/impl/FileDownloadServiceImpl.java
  src/main/resources/application-test.properties
  src/test/java/kodanect/domain/article/controller/ArticleControllerIntegrationTest.java
  src/test/java/kodanect/domain/article/controller/ArticleControllerTest.java
  src/test/java/kodanect/domain/article/controller/ArticleExceptionHandlerTest.java
Labels: bug

#82 Refactor/article
  Jenkinsfile
  pom.xml
  src/main/java/kodanect/common/config/WebMvcConfig.java
  src/main/java/kodanect/common/exception/config/ArticleExceptionHandler.java
  src/main/java/kodanect/domain/article/controller/ArticleController.java
  src/main/java/kodanect/domain/article/dto/DownloadFile.java
  src/main/java/kodanect/domain/article/dto/SearchCondition.java
  src/main/java/kodanect/domain/article/repository/ArticleRepositoryImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/egovframework/message/message-common.properties
  src/main/resources/log4j2-dev.xml
  src/main/resources/log4j2-prod.xml
  src/main/resources/log4j2.xml
  src/test/java/kodanect/domain/article/controller/ArticleControllerTest.java
  src/test/java/kodanect/domain/article/service/ArticleServiceImplTest.java
Labels: refactor

#48 Refactor/donation
  Jenkinsfile
  src/main/java/kodanect/common/exception/config/GlobalExcepHndlr.java
  src/main/java/kodanect/domain/donation/controller/DonationController.java
  src/main/java/kodanect/domain/donation/dto/OffsetBasedPageRequest.java
  src/main/java/kodanect/domain/donation/dto/request/DonationCommentCreateRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryCommentModifyRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryCreateRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryModifyRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/VerifyCommentPasscodeDto.java
  src/main/java/kodanect/domain/donation/dto/response/DonationStoryCommentDto.java
  src/main/java/kodanect/domain/donation/dto/response/DonationStoryDetailDto.java
  src/main/java/kodanect/domain/donation/dto/response/DonationStoryListDto.java
  src/main/java/kodanect/domain/donation/dto/response/DonationStoryWriteFormDto.java
  src/main/java/kodanect/domain/donation/exception/DonationCommentNotFoundException.java
  src/main/java/kodanect/domain/donation/exception/DonationExceptionHandler.java
  src/main/java/kodanect/domain/donation/exception/PasscodeMismatchException.java
  src/main/java/kodanect/domain/donation/repository/DonationCommentRepository.java
  src/main/java/kodanect/domain/donation/repository/DonationRepository.java
  src/main/java/kodanect/domain/donation/service/DonationCommentService.java
  src/main/java/kodanect/domain/donation/service/DonationService.java
  src/main/java/kodanect/domain/donation/service/impl/CaptchaService.java
  src/main/java/kodanect/domain/donation/service/impl/DonationCommentServiceImpl.java
  src/main/java/kodanect/domain/donation/service/impl/DonationServiceImpl.java
  src/main/java/kodanect/domain/recipient/controller/RecipientCommentController.java
  src/main/java/kodanect/domain/recipient/entity/RecipientEntity.java
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/controller/DonationControllerTest.java
  src/test/java/kodanect/domain/donation/service/DonationCommentServiceImplTest.java
  src/test/java/kodanect/domain/donation/service/DonationCommentServiceTest.java
  src/test/java/kodanect/domain/donation/service/DonationServiceImplTest.java
  src/test/java/kodanect/domain/donation/service/DonationServiceTest.java
Labels: refactor

#87 fix/recipientletters
  .gitignore
  package-lock.json
  package.json
  src/main/java/kodanect/domain/recipient/controller/RecipientController.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
Labels: bug

#90 fix/recipientletters
  src/test/java/kodanect/domain/recipient/repository/RecipientCommentRepositoryTest.java
Labels: bug

#92 Feature/search cursor pagination
  src/main/java/kodanect/common/exception/config/MessageKeys.java
  src/main/java/kodanect/common/validation/PaginationValidator.java
  src/main/java/kodanect/domain/remembrance/controller/MemorialCommentController.java
  src/main/java/kodanect/domain/remembrance/controller/MemorialController.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialResponse.java
  src/main/java/kodanect/domain/remembrance/dto/common/MemorialNextCursor.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidPaginationException.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialRepository.java
  src/main/java/kodanect/domain/remembrance/service/MemorialService.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialServiceImpl.java
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/remembrance/controller/MemorialCommentControllerExceptionTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialCommentControllerTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialControllerExceptionTest.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialControllerTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialServiceImplTest.java
Labels: refactor

#76 Feature/heaven letter
  src/main/java/kodanect/common/exception/config/MessageKeys.java
  src/main/java/kodanect/common/util/HeavenCommentFinder.java
  src/main/java/kodanect/common/util/HeavenFinder.java
  src/main/java/kodanect/common/validation/HeavenValidator.java
  src/main/java/kodanect/domain/heaven/controller/HeavenCommentController.java
  src/main/java/kodanect/domain/heaven/controller/HeavenController.java
  src/main/java/kodanect/domain/heaven/dto/request/HeavenCommentCreateRequest.java
  src/main/java/kodanect/domain/heaven/dto/request/HeavenCommentUpdateRequest.java
  src/main/java/kodanect/domain/heaven/dto/request/HeavenCommentVerifyRequest.java
  src/main/java/kodanect/domain/heaven/dto/request/HeavenCreateRequest.java
  src/main/java/kodanect/domain/heaven/dto/request/HeavenUpdateRequest.java
  src/main/java/kodanect/domain/heaven/dto/request/HeavenVerifyRequest.java
  src/main/java/kodanect/domain/heaven/dto/response/HeavenCommentResponse.java
  src/main/java/kodanect/domain/heaven/dto/response/HeavenDetailResponse.java
  src/main/java/kodanect/domain/heaven/dto/response/HeavenResponse.java
  src/main/java/kodanect/domain/heaven/dto/response/MemorialHeavenResponse.java
  src/main/java/kodanect/domain/heaven/entity/Heaven.java
  src/main/java/kodanect/domain/heaven/entity/HeavenComment.java
  src/main/java/kodanect/domain/heaven/exception/DonorInformationMismatchException.java
  src/main/java/kodanect/domain/heaven/exception/FileStorageException.java
  src/main/java/kodanect/domain/heaven/exception/HeavenCommentInformationMismatchException.java
  src/main/java/kodanect/domain/heaven/exception/HeavenCommentNotFoundException.java
  src/main/java/kodanect/domain/heaven/exception/HeavenNotFoundException.java
  src/main/java/kodanect/domain/heaven/exception/InvalidTypeException.java
  src/main/java/kodanect/domain/heaven/exception/PasswordMismatchException.java
  src/main/java/kodanect/domain/heaven/repository/HeavenCommentRepository.java
  src/main/java/kodanect/domain/heaven/repository/HeavenRepository.java
  src/main/java/kodanect/domain/heaven/service/HeavenCommentService.java
  src/main/java/kodanect/domain/heaven/service/HeavenService.java
  src/main/java/kodanect/domain/heaven/service/impl/HeavenCommentServiceImpl.java
  src/main/java/kodanect/domain/heaven/service/impl/HeavenServiceImpl.java
  src/test/java/kodanect/domain/heaven/controller/HeavenControllerTest.java
  src/test/java/kodanect/domain/heaven/service/impl/HeavenServiceImplTest.java
Labels: feature

#99 refactor/recipientletters
  src/main/java/kodanect/common/config/WebMvcConfig.java
  src/main/java/kodanect/common/imageupload/ImageUploadController.java
  src/main/java/kodanect/common/imageupload/ImageUploadService.java
  src/main/java/kodanect/domain/recipient/controller/RecipientCommentController.java
  src/main/java/kodanect/domain/recipient/controller/RecipientController.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentAuthRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentUpdateRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientDetailResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientListResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientRequestDto.java
  src/main/java/kodanect/domain/recipient/entity/RecipientCommentEntity.java
  src/main/java/kodanect/domain/recipient/entity/RecipientEntity.java
  src/main/java/kodanect/domain/recipient/service/RecipientCommentService.java
  src/main/java/kodanect/domain/recipient/service/RecipientService.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImpl.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/test/java/kodanect/domain/recipient/controller/RecipientCommentControllerTest.java
  src/test/java/kodanect/domain/recipient/controller/RecipientControllerTest.java
  src/test/java/kodanect/domain/recipient/repository/RecipientCommentRepositoryTest.java
  src/test/java/kodanect/domain/recipient/repository/RecipientRepositoryTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImplTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceContentValidationTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceImplTest.java
Labels: refactor

#101 Feature/remembrance anony letters
  src/main/java/kodanect/common/util/FormatUtils.java
  src/main/java/kodanect/common/validation/PaginationValidator.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialDetailResponse.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialResponse.java
  src/main/java/kodanect/domain/remembrance/repository/MemorialRepository.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialServiceImpl.java
  src/test/java/kodanect/domain/remembrance/TestMemorialResponse.java
  src/test/java/kodanect/domain/remembrance/controller/MemorialControllerTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialServiceImplTest.java
Labels: feature

#100 Chore/donation PR
  .gitignore
  src/main/java/kodanect/domain/donation/controller/DonationController.java
  src/main/java/kodanect/domain/donation/controller/ImageFileUploadController.java
  src/main/java/kodanect/domain/donation/dto/request/DonationCommentCreateRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryCommentModifyRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryCreateRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryModifyRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/VerifyCommentPasscodeDto.java
  src/main/java/kodanect/domain/donation/dto/request/VerifyStoryPasscodeDto.java
  src/main/java/kodanect/domain/donation/dto/response/DonationStoryModifyDto.java
  src/main/java/kodanect/domain/donation/entity/DonationStory.java
  src/main/java/kodanect/domain/donation/entity/DonationStoryComment.java
  src/main/java/kodanect/domain/donation/service/DonationService.java
  src/main/java/kodanect/domain/donation/service/impl/DonationCommentServiceImpl.java
  src/main/java/kodanect/domain/donation/service/impl/DonationServiceImpl.java
  src/main/resources/ValidationMessages.properties
  src/main/resources/application-dev.properties
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/controller/DonationControllerTest.java
  src/test/java/kodanect/domain/donation/service/DonationCommentServiceImplTest.java
  src/test/java/kodanect/domain/donation/service/DonationServiceImplTest.java
Labels: feature

#108 Feature/remembrance html normalizer
  src/main/java/kodanect/common/exception/config/MessageKeys.java
  src/main/java/kodanect/common/util/FormatUtils.java
  src/main/java/kodanect/common/util/MemorialHtmlNormalizer.java
  src/main/java/kodanect/domain/remembrance/controller/MemorialController.java
  src/main/java/kodanect/domain/remembrance/dto/MemorialDetailResponse.java
  src/main/java/kodanect/domain/remembrance/exception/InvalidContentsException.java
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialServiceImpl.java
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/remembrance/controller/MemorialControllerTest.java
  src/test/java/kodanect/domain/remembrance/service/MemorialServiceImplTest.java
Labels: feature

#107 refactor/recipientletters
  src/main/java/kodanect/common/exception/config/RecipientExceptionHandler.java
  src/main/java/kodanect/domain/recipient/controller/RecipientCommentController.java
  src/main/java/kodanect/domain/recipient/controller/RecipientController.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentUpdateRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientDetailResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientListResponseDto.java
  src/main/java/kodanect/domain/recipient/exception/RecipientInvalidPasscodeException.java
  src/main/java/kodanect/domain/recipient/service/RecipientCommentService.java
  src/main/java/kodanect/domain/recipient/service/RecipientService.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImpl.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
  src/test/java/kodanect/domain/recipient/controller/RecipientControllerTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImplTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceImplTest.java
Labels: refactor

#106 Chore/donation FileUpload 기능
  src/main/java/kodanect/domain/donation/controller/DonationController.java
  src/main/java/kodanect/domain/donation/controller/ImageFileUploadController.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryCommentModifyRequestDto.java
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryCreateRequestDto.java
  src/main/java/kodanect/domain/donation/entity/DonationStory.java
  src/main/java/kodanect/domain/donation/entity/DonationStoryComment.java
  src/main/java/kodanect/domain/donation/service/DonationService.java
  src/main/java/kodanect/domain/donation/service/impl/DonationCommentServiceImpl.java
  src/main/java/kodanect/domain/donation/service/impl/DonationServiceImpl.java
  src/main/resources/application-prod.properties
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/donation/controller/DonationControllerTest.java
  src/test/java/kodanect/domain/donation/service/DonationServiceImplTest.java
Labels: refactor

#116 refactor/recipientletters
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientDetailResponseDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientRequestDto.java
  src/main/java/kodanect/domain/recipient/entity/RecipientEntity.java
  src/main/java/kodanect/domain/recipient/repository/RecipientCommentRepository.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
  src/test/java/kodanect/domain/recipient/controller/RecipientCommentControllerTest.java
  src/test/java/kodanect/domain/recipient/controller/RecipientControllerTest.java
  src/test/java/kodanect/domain/recipient/repository/RecipientCommentRepositoryTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImplTest.java
  src/test/java/kodanect/domain/recipient/service/impl/RecipientServiceImplTest.java
Labels: refactor

#122 feat: OWASP Dependency-Check 정적 분석 적용
  Jenkinsfile
  pom.xml
  scripts/run-changed-tests.sh
Labels: feature

#123 Fix imageparsing_25_0620
  src/main/java/kodanect/common/imageupload/ImageUploadController.java
  src/main/java/kodanect/common/imageupload/ImageUploadService.java
  src/main/java/kodanect/domain/recipient/service/impl/RecipientServiceImpl.java
Labels: refactor

#125 Refactor/recipientletters/imageparsing
  src/main/java/kodanect/domain/recipient/dto/RecipientDetailResponseDto.java
Labels: refactor

#128 Refactor/recipientletters/imageparsing
  src/main/java/kodanect/domain/recipient/controller/RecipientCommentController.java
  src/main/java/kodanect/domain/recipient/controller/RecipientController.java
Labels: refactor

#129 Feature: Spring 컨테이너 메모리 설정 최적화 및 Docker 구성 개선
  docker-compose.dev.yml
  docker-compose.prod.yml
Labels: feature

#130 Refactor/donation fix
  src/main/java/kodanect/domain/donation/controller/.gitkeep
  src/main/java/kodanect/domain/donation/controller/DonationController.java
  src/main/java/kodanect/domain/donation/dto/.gitkeep
  src/main/java/kodanect/domain/donation/dto/request/DonationStoryCommentModifyRequestDto.java
  src/main/java/kodanect/domain/donation/entity/.gitkeep
  src/main/java/kodanect/domain/donation/entity/DonationStoryComment.java
  src/main/java/kodanect/domain/donation/repository/.gitkeep
  src/main/java/kodanect/domain/donation/repository/DonationCommentRepository.java
  src/main/java/kodanect/domain/donation/service/.gitkeep
  src/main/java/kodanect/domain/donation/service/impl/DonationCommentServiceImpl.java
  src/main/java/kodanect/domain/donation/service/impl/DonationServiceImpl.java
  src/main/java/kodanect/domain/heaven/service/FileService.java
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/donation/controller/DonationControllerTest.java
  src/test/java/kodanect/domain/donation/service/DonationCommentServiceImplTest.java
Labels: refactor

#137 fix / recipientletters/imageparsing
  src/main/java/kodanect/domain/recipient/service/impl/RecipientCommentServiceImpl.java
Labels: bug

#143 chore : front inquiry 적용_25_0622
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientCommentUpdateRequestDto.java
  src/main/java/kodanect/domain/recipient/dto/RecipientRequestDto.java
Labels: refactor

#142 Chore/donation fix title condition
  src/main/java/kodanect/domain/donation/exception/InvalidWriterException.java
  src/main/java/kodanect/domain/donation/service/impl/DonationCommentServiceImpl.java
  src/main/java/kodanect/domain/donation/service/impl/DonationServiceImpl.java
  src/main/java/kodanect/domain/heaven/service/FileService.java
  src/main/resources/egovframework/message/message-common.properties
  src/test/java/kodanect/domain/donation/service/DonationCommentServiceImplTest.java
Labels: refactor

#147 refactor: 상세 조회 시 readLock 선점 로직 추가
  src/main/java/kodanect/domain/remembrance/service/impl/MemorialServiceImpl.java
Labels: refactor
